[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

#[deploy]
#healthcheckPath = "/actuator/health"
#healthcheckTimeout = 120
#restartPolicyType = "on_failure"
#restartPolicyMaxRetries = 3
